services:
  asana-tool-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - 3000:3000
    image: asana-tool-web
    container_name: asana-tool-web
    environment:
     - AUTH_SECRET=${AUTH_SECRET}
     - AUTH_TRUST_HOST=true
     - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
     - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
     - AUTH_URL=${AUTH_URL}
     - ASANA_TOKEN=${ASANA_TOKEN}
     - ASANA_WORKSPACE=${ASANA_WORKSPACE}

  redis:
    image: redis:alpine
    container_name: redis-asana-tool-web
    restart: always
    ports:
      - 6379:6379

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-asana-tool-web
    command: tunnel --no-autoupdate run --token
      ${CF_TOKEN}
    restart: always
    network_mode: host
